### ISSUE TITLE
Work on any MD file

### ISSUE THREAD

**Issue by singularityhacker** [morkro/chrome-gist-word-count#1]
Is there any way this could be changed to work on any MD file and not just gist's? I switched from google docs to git for all my writing and a word count is going to be extremely useful. Thank you for all the hard work you have put into this.

**Comment by morkro** [comment]
Hey 👋  I don't quite understand, can you elaborate?

Do you mean this extension to also count words in Markdown files on other websites?

**Comment by singularityhacker** [comment]
Sure, sorry for not being more clear. There are now two issues.
1. The chrome extension doesn't seem to be working on gist's anymore. See [this](https://gist.github.com/singularityhacker/1df3e3ab489e69c31b9f99b2dbe68832) for example.
2. My original request was to see if it could be modified to work on MD files in any GitHub repository. Possibly next to the other file data displayed [here](https://i.imgur.com/l6pbTaZ.png)

**Comment by morkro** [comment]
Oh right, now I understand!

> 1. The chrome extension doesn't seem to be working on gist's anymore. See this for example.

This is strange. It works on other files for me, but not on this one. I will investigate.

> 2. My original request was to see if it could be modified to work on MD files in any GitHub repository. Possibly next to the other file data displayed here

Good idea, I like that. Should be doable for sure.

**Comment by morkro** [comment]
@singularityhacker I have fixed the issue and submitted a new version to the Chrome Web Store. I am awaiting a review.

**Comment by singularityhacker** [comment]
This is awesome!! I will keep an eye on when it updates. Can't wait to try it out.
